const FeedData = [
    {
        "Booking_ID": 10001,
        "Customer_ID": '001',
        "Customer_Name": "Charlie",
        "Event": {
            "Event_ID": 10001,
            "Img_Url": "golf.jpg",
            "Event_Category": "Golf",
            "Event_Name": "Round of Golf",
            "Event_Start_Date": "Nov 10-29, 2022",
            "Event_End_Date": "Nov 10-29, 2022",
            "Event_Location": "Sindalah City",
            "Overall_Event_Rating": 5.0,
            "Total_reviews":"123"
        },
        "Review": {
            "Date": "Nov 17, 2022",
            "Overall_Rating": 5,
            "Feedback": "Great experience!",
            "Suggestion": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elit.",
        }
    },
    {
        "Booking_ID": 10001,
        "Customer_ID": '001',
        "Customer_Name": "Charlie",
        "Event": {
            "Event_ID": 10002,
            "Img_Url": "dive.jpg",
            "Event_Category": "Golf",
            "Event_Name": "Dive into Exciting",
            "Event_Start_Date": "Nov 10-29, 2022",
            "Event_End_Date": "Nov 10-29, 2022",
            "Event_Location": "Sindalah City",
            "Overall_Event_Rating": 5.0,
            "Total_reviews":"123"
        },
        "Review": {
            "Date": "Nov 17, 2022",
            "Overall_Rating": "",
            "Feedback": "",
            "Suggestion": "",
        }
    },
    {
        "Booking_ID": 10001,
        "Customer_ID": '001',
        "Customer_Name": "Charlie",
        "Event": {
            "Event_ID": 10003,
            "Img_Url": "surfing.jpg",
            "Event_Category": "Golf",
            "Event_Name": "Surfing at leisure",
            "Event_Start_Date": "Nov 10-29, 2022",
            "Event_End_Date": "Nov 10-29, 2022",
            "Event_Location": "Sindalah City",
            "Overall_Event_Rating": 4.9,
            "Total_reviews":"123"
        },
        "Review": {
            "Date": "Nov 17, 2022",
            "Overall_Rating": 4.3,
            "Feedback": "Thank you Unified Guests for this great experience!",
            "Suggestion": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elit.",
        }
    },
    {
        "Booking_ID": 10001,
        "Customer_ID": '001',
        "Customer_Name": "Charlie",
        "Event": {
            "Event_ID": 10001,
            "Img_Url": "golf.jpg",
            "Event_Category": "Golf",
            "Event_Name": "Round of Golf",
            "Event_Start_Date": "Nov 10-29, 2022",
            "Event_End_Date": "Nov 10-29, 2022",
            "Event_Location": "Sindalah City",
            "Overall_Event_Rating": 5.0,
            "Total_reviews":"123"
        },
        "Review": {
            "Date": "Nov 17, 2022",
            "Overall_Rating":3.5,
            "Feedback": "Great experience!",
            "Suggestion": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elit.",
        }
    },
]
const FeedbackData = [
    {
        "Booking_ID":10001,
        "Customer_ID":'001',
        "Customer_Name":"Jane Mathew",
        "Customer_Persona":"UHNWI",
        "Age":48,
        "Gender":"Female",
        "Event_Category":"Concerts",
        "Event_Description":"Singing",
        "Operator_ID":10006,
        "Quality":4,
        "Facilities":4,
        "Staff":4,
        "Service":3,
        "Operator":4,
        "Overall_Rating":3.8,
        "Feedback":"Event was awesome",
        "Suggestion":"Need to improve sound system",
    },
    {
        "Booking_ID":10001,
        "Customer_ID":'002',
        "Customer_Name":"Shane Mathew",
        "Customer_Persona":"UHNWI",
        "Age":50,
        "Gender":"Male",
        "Event_Category":"Concerts",
        "Event_Description":"Singing",
        "Operator_ID":10006,
        "Quality":5,
        "Facilities":5,
        "Staff":5,
        "Service":4,
        "Operator":5,
        "Overall_Rating":4.8,
        "Feedback":"Event management was good",
        "Suggestion":"Rappers also should participate",
    },
    {
        "Booking_ID":10001,
        "Customer_ID":'003',
        "Customer_Name":"Rose Mathew",
        "Customer_Persona":"UHNWI w",
        "Age":17,
        "Gender":"Female",
        "Event_Category":"Concerts",
        "Event_Description":"Singing",
        "Operator_ID":10006,
        "Quality":4,
        "Facilities":5,
        "Staff":4,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.6,
        "Feedback":"NA",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10002,
        "Customer_ID":'001',
        "Customer_Name":"David Arthor",
        "Customer_Persona":"New Saudis",
        "Age":38,
        "Gender":"Male",
        "Event_Category":"Golf",
        "Event_Description":"Mens Golf League",
        "Operator_ID":20004,
        "Quality":5,
        "Facilities":5,
        "Staff":5,
        "Service":5,
        "Operator":4,
        "Overall_Rating":4.8,
        "Feedback":"Customer Service is always prompt when I have questions. Site is pretty intuitive and easy to use. Recent upgrades are a plus, not a minus",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10002,
        "Customer_ID":'002',
        "Customer_Name":"SimOn Arthor",
        "Customer_Persona":"New Saudis",
        "Age":35,
        "Gender":"Female",
        "Event_Category":"Concerts",
        "Event_Description":"Music Type-Classic",
        "Operator_ID":20005,
        "Quality":4,
        "Facilities":5,
        "Staff":4,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.6,
        "Feedback":"NA",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10002,
        "Customer_ID":'003',
        "Customer_Name":"Jon Arthor",
        "Customer_Persona":"New Saudis",
        "Age":58,
        "Gender":"Male",
        "Event_Category":"Golf",
        "Event_Description":"Mens Golf League",
        "Operator_ID":20004,
        "Quality":3,
        "Facilities":4,
        "Staff":5,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.4,
        "Feedback":"Another great experience this year!",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10002,
        "Customer_ID":'004',
        "Customer_Name":"Sheemzy Arthor",
        "Customer_Persona":"New Saudis",
        "Age":'06',
        "Gender":"Female",
        "Event_Category":"Water Sports",
        "Event_Description":"Swimming game for below 18 years Kids",
        "Operator_ID":20003,
        "Quality":4,
        "Facilities":4,
        "Staff":4,
        "Service":3,
        "Operator":4,
        "Overall_Rating":3.8,
        "Feedback":"NA",
        "Suggestion":"NA",
    },

    {
        "Booking_ID":10003,
        "Customer_ID":'001',
        "Customer_Name":"Michel Dom",
        "Customer_Persona":"NEOM Residents",
        "Age":44,
        "Gender":"Male",
        "Event_Category":"Exhibitions",
        "Event_Description":"Historical Book",
        "Operator_ID":20008,
        "Quality":5,
        "Facilities":5,
        "Staff":5,
        "Service":5,
        "Operator":4,
        "Overall_Rating":4.8,
        "Feedback":"Fair Deal book points",
        "Suggestion":"Needs to keep books for all countries history",
    },
    {
        "Booking_ID":10003,
        "Customer_ID":'002',
        "Customer_Name":"Lara Dom",
        "Customer_Persona":"NEOM Residents",
        "Age":41,
        "Gender":"Female",
        "Event_Category":"Exhibitions",
        "Event_Description":"Historical Book",
        "Operator_ID":20008,
        "Quality":4,
        "Facilities":5,
        "Staff":4,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.6,
        "Feedback":"NA",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10003,
        "Customer_ID":'003',
        "Customer_Name":"Petriock Dom",
        "Customer_Persona":"NEOM Residents",
        "Age":11,
        "Gender":"Male",
        "Event_Category":"Exhibitions",
        "Event_Description":"Historical Book",
        "Operator_ID":20008,
        "Quality":4,
        "Facilities":4,
        "Staff":5,
        "Service":5,
        "Operator":4,
        "Overall_Rating":4.4,
        "Feedback":"NA",
        "Suggestion":"NA",
    },

    {
        "Booking_ID":10004,
        "Customer_ID":'001',
        "Customer_Name":"Sachin Tendulkar",
        "Customer_Persona":"International Celebrity",
        "Age":48,
        "Gender":"Male",
        "Event_Category":"Plays",
        "Event_Description":"Cricket game with limited space in net",
        "Operator_ID":20003,
        "Quality":5,
        "Facilities":5,
        "Staff":5,
        "Service":5,
        "Operator":4,
        "Overall_Rating":4.8,
        "Feedback":"I like the game and services",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10004,
        "Customer_ID":'002',
        "Customer_Name":"Sushma Tendulkar",
        "Customer_Persona":"International Celebrity",
        "Age":45,
        "Gender":"Female",
        "Event_Category":"Concerts",
        "Event_Description":"Music Type - Classic",
        "Operator_ID":20005,
        "Quality":4,
        "Facilities":5,
        "Staff":4,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.6,
        "Feedback":"Music system was awesome",
        "Suggestion":"NA",
    }
,
    {
        "Booking_ID":10004,
        "Customer_ID":'003',
        "Customer_Name":"Arjun Tendulkar",
        "Customer_Persona":"International Celebrity",
        "Age":16,
        "Gender":"Male",
        "Event_Category":"Plays",
        "Event_Description":"Cricket game with limited space in net",
        "Operator_ID":20003,
        "Quality":5,
        "Facilities":5,
        "Staff":4,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.8,
        "Feedback":"awesome ground and climate",
        "Suggestion":"increase the per match overs",
    },
    {
        "Booking_ID":10005,
        "Customer_ID":'001',
        "Customer_Name":"Akshay Kumar",
        "Customer_Persona":"Event Guests",
        "Age":51,
        "Gender":"Male",
        "Event_Category":"Comedy Shows",
        "Event_Description":"CLive comedy Performance infront of Audience",
        "Operator_ID":20001,
        "Quality":4,
        "Facilities":5,
        "Staff":4,
        "Service":5,
        "Operator":5,
        "Overall_Rating":4.6,
        "Feedback":"NA",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10005,
        "Customer_ID":'002',
        "Customer_Name":"Kiran Kumar",
        "Customer_Persona":"Event Guests",
        "Age":47,
        "Gender":"Female",
        "Event_Category":"Comedy Shows",
        "Event_Description":"CLive comedy Performance infront of Audience",
        "Operator_ID":20001,
        "Quality":5,
        "Facilities":5,
        "Staff":5,
        "Service":4,
        "Operator":4,
        "Overall_Rating":4.6,
        "Feedback":"NA",
        "Suggestion":"NA",
    },
    {
        "Booking_ID":10005,
        "Customer_ID":'003',
        "Customer_Name":"Salina Kumar",
        "Customer_Persona":"Event Guests",
        "Age":17,
        "Gender":"Female",
        "Event_Category":"Comedy Shows",
        "Event_Description":"CLive comedy Performance infront of Audience",
        "Operator_ID":20001,
        "Quality":5,
        "Facilities":5,
        "Staff":5,
        "Service":5,
        "Operator":4,
        "Overall_Rating":4.8,
        "Feedback":"NA",
        "Suggestion":"NA",
    },

    {
        "Booking_ID":10005,
        "Customer_ID":'003',
        "Customer_Name":"Raj Kumar",
        "Customer_Persona":"Event Guests",
        "Age":13,
        "Gender":"Male",
        "Event_Category":"Comedy Shows",
        "Event_Description":"CLive comedy Performance infront of Audience",
        "Operator_ID":20001,
        "Quality":5,
        "Facilities":4,
        "Staff":5,
        "Service":4,
        "Operator":3,
        "Overall_Rating":4.4,
        "Feedback":"NA",
        "Suggestion":"NA",
    },

]
export {FeedbackData, FeedData};
