const RecommendationData = [
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},

    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
]
const eventDetailImage = [
    {img:"Image120.jpg"},
    {img:"Image118.jpg"},
    {img:"Image122.jpg"},
    {img:"Image121.jpg"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const Treading = [
    {img:"trending1.jpg", rank:"one.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rank:"two.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg", rank:"three.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg", rank:"four.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rank:"five.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const SliderCardData = [
    {img:"trending1.jpg", rank:"one.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"recommend2.jpg", rank:"two.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"trending2.jpg", rank:"three.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"trending1.jpg", rank:"four.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod et dolore magna aliquyam erat…"},
    {img:"recommend2.jpg", rank:"five.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod dolore magna aliquyam erat…"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const DashboardEventDetail =
[

    {
      "Event_ID": 10002,
      "Operator_ID": 20002,
      "url":'golf.jpg',
      "Operator_Name": "Dark Roast",
      "Event_Category": "Fashion Shows",
      "Event_Name": "Round of Golf",
      "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
      "Event_Start_Date": "11/10/2022",
      "Event_End_Date": "11/29/2022",
      "Event_Start_Time": "7:00 PM",
      "Event_End_Time": "11:00 PM",
      "Seat_Booking_Availability": 20,
      "Event_Location": "Sindalah City",
      "Event_Status": "Completed",
      "Event_Capacity": 200,
      "Overall_Event_Rating": 4.8,
      "Operator_Rating": 4,
        "Client_Booked": true,
        "imgurl":
          {"img": "golf.jpg"},
        
    },
    {
      "Event_ID": 10003,
      "Operator_ID": 20003,
      "url":'surfing.jpg',
      "Operator_Name": "Basket of gold",
      "Event_Category": "Plays",
      "Event_Name": "Surfing at leasure",
      "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
      "Event_Start_Date": "11/11/2022",
      "Event_End_Date": "11/30/2022",
      "Event_Start_Time": "10:00 PM",
      "Event_End_Time": "05:00 PM",
      "Seat_Booking_Availability": 20,
      "Event_Location": "Sindalah City",
      "Event_Status": "Completed",
      "Event_Capacity": 300,
      "Overall_Event_Rating": 4.6,
      "Operator_Rating": 5,
        "Client_Booked": true,
        "imgurl":
        {"img": "golf.jpg"},
        
    },
    {
      "Event_ID": 10004,
      "Operator_ID": 20003,
      "url":'dive.jpg',
      "Operator_Name": "Basket of gold",
      "Event_Category": "Water Activity",
      "Event_Name": "Dive into Exciting",
      "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
      "Event_Start_Date": "11/10/2022",
      "Event_End_Date": "11/29/2022",
      "Event_Start_Time": "03:00 PM",
      "Event_End_Time": "05:00 PM",
      "Seat_Booking_Availability": 20,
      "Event_Location": "Sindalah City",
      "Event_Status": "Completed",
      "Event_Capacity": 100,
      "Overall_Event_Rating": 4.6,
      "Operator_Rating": 3,
        "Client_Booked": true,
        "imgurl":
        {"img": "golf.jpg"},
        
    },
    {
      "Event_ID": 10002,
      "Operator_ID": 20002,
      "url":'golf.jpg',
      "Operator_Name": "Dark Roast",
      "Event_Category": "Fashion Shows",
      "Event_Name": "Round of Golf",
      "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
      "Event_Start_Date": "11/10/2022",
      "Event_End_Date": "11/29/2022",
      "Event_Start_Time": "7:00 PM",
      "Event_End_Time": "11:00 PM",
      "Seat_Booking_Availability": 20,
      "Event_Location": "Sindalah City",
      "Event_Status": "Completed",
      "Event_Capacity": 200,
      "Overall_Event_Rating": 4.8,
      "Operator_Rating": 4,
        "Client_Booked": true,
        "imgurl":
          {"img": "golf.jpg"},
        
    },
  ]
const EventDetail =
    [

        {
          "Event_ID": 10002,
          "Operator_ID": 20002,
          "url":'golf.jpg',
          "Operator_Name": "Dark Roast",
          "Event_Category": "Fashion Shows",
          "Event_Name": "Round of Golf",
          "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "7:00 PM",
          "Event_End_Time": "11:00 PM",
          "Seat_Booking_Availability": 20,
          "Event_Location": "Sindalah City",
          "Event_Status": "Completed",
          "Event_Capacity": 200,
          "Overall_Event_Rating": 4.8,
          "Operator_Rating": 4,
            "Client_Booked": true,
        },
        {
          "Event_ID": 10003,
          "Operator_ID": 20003,
          "url":'surfing.jpg',
          "Operator_Name": "Basket of gold",
          "Event_Category": "Plays",
          "Event_Name": "Surfing at leasure",
          "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
          "Event_Start_Date": "11/11/2022",
          "Event_End_Date": "11/30/2022",
          "Event_Start_Time": "10:00 PM",
          "Event_End_Time": "05:00 PM",
          "Seat_Booking_Availability": 20,
          "Event_Location": "Sindalah City",
          "Event_Status": "Completed",
          "Event_Capacity": 300,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 5,
            "Client_Booked": true,
        },
        {
          "Event_ID": 10004,
          "Operator_ID": 20003,
          "url":'dive.jpg',
          "Operator_Name": "Basket of gold",
          "Event_Category": "Water Activity",
          "Event_Name": "Dive into Exciting",
          "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "03:00 PM",
          "Event_End_Time": "05:00 PM",
          "Seat_Booking_Availability": 20,
          "Event_Location": "Sindalah City",
          "Event_Status": "Completed",
          "Event_Capacity": 100,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3,
            "Client_Booked": true,
        },
        {
          "Event_ID": 10005,
          "Operator_ID": 20004,
          "url":'golf.jpg',
          "Operator_Name": "Northern lights",
          "Event_Category": "Golf",
          "Event_Name": "Golf tournament",
          "Event_Description": "Mens Golf League",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "02:00 PM",
          "Event_End_Time": "05:00 PM",
          "Seat_Booking_Availability": 30,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 250,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 4
        },
        {
          "Event_ID": 10006,
          "Operator_ID": 20005,
          "url":'surfing.jpg',
          "Operator_Name": "Eden Spring",
          "Event_Category": "concerts",
          "Event_Name": "Singing",
          "Event_Description": "Music Type - Rock",
          "Event_Start_Date": "11/12/2022",
          "Event_End_Date": "11/30/2022",
          "Event_Start_Time": "07:30 PM",
          "Event_End_Time": "11:00 PM",
          "Seat_Booking_Availability": 10,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 100,
          "Overall_Event_Rating": 4.4,
          "Operator_Rating": 3
        },
        {
          "Event_ID": 10007,
          "Operator_ID": 20005,
          "Operator_Name": "Eden Spring",
          "Event_Category": "Cooking ",
          "Event_Name": "cooking class",
          "Event_Description": "Thai Cooking Class",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "07:30 PM",
          "Event_End_Time": "11:00 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 150,
          "Overall_Event_Rating": 4.4,
          "Operator_Rating": 4
        },
        {
          "Event_ID": 10008,
          "Operator_ID": 20006,
          "Operator_Name": "River Stone",
          "Event_Category": "Talks ",
          "Event_Name": "Talks Shows",
          "Event_Description": "Live Talk Shows",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "08:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 20,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 400,
          "Overall_Event_Rating": 4.8,
          "Operator_Rating": 5
        },
        {
          "Event_ID": 10009,
          "Operator_ID": 20007,
          "Operator_Name": "Dancing leaf",
          "Event_Category": "Kite Surfing ",
          "Event_Name": "Kite Surfing",
          "Event_Description": "Age above 18+",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "10:00 PM",
          "Event_End_Time": "03:00 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 200,
          "Overall_Event_Rating": 4.4,
          "Operator_Rating": 4
        },
        {
          "Event_ID": 100010,
          "Operator_ID": 20008,
          "Operator_Name": "Painted Desert",
          "Event_Category": "Exhibitions ",
          "Event_Name": "Book Exhibitions",
          "Event_Description": "Historical Book Exhibitions",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/29/2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 15,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 200,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3
        },
        {
          "Event_ID": 100011,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event_Name": "Jazz Concert",
          "Event_Description": "Steam Down",
          "Event_Start_Date": "11/11/2022",
          "Event_End_Date": "11/11/2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 20,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 100,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3
        },
        {
          "Event_ID": 100012,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event_Name": "Rock Concert",
          "Event_Description": "Rolling Stone",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/10/2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 50,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3
        },
        {
          "Event_ID": 100013,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event_Name": "Piano Classes",
          "Event_Description": "Piano basics",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/10/2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 20,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3
        },
        {
          "Event_ID": 100014,
          "Operator_ID": 20003,
          "Operator_Name": "Basket of gold",
          "Event_Category": "carnival",
          "Event_Name": "Sweet Wonderlaw",
          "Event_Description": "Weekly carnival",
          "Event_Start_Date": "11/10/2022",
          "Event_End_Date": "11/10/2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah City",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 20,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3
        }
      ]

const Profile = [
    {
        "Booking_ID":10001,
        "Customer_ID":'001',
        "Customer_Name":"Charlie",
        "Customer_Image":"filepath",
        "Contact_Number":8899112233,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":48,
        "dop":'08/01/1979',
        "Gender":"female",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Golf, Rooms",
        "Dislikes":"Walking for Long",
        "Other/Preferences":"NA",


    },
    {
        "Booking_ID":10001,
        "Customer_ID":'002',
        "Customer_Name":"Shane Mathew",
        "Customer_Image":"filepath",
        "Contact_Number":8699114455,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":50,
        "Gender":"male",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Music, Exploring",
        "Dislikes":"Walking for Long",
        "Other/Preferences":"NA",


    },

    {
        "Booking_ID":10001,
        "Customer_ID":'003',
        "Customer_Name":"Rose Mathey",
        "Customer_Image":"filepath",
        "Contact_Number":9877665544,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":48,
        "Gender":"female",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Cooking",
        "Dislikes":"Chinese food",
        "Other/Preferences":"NA",
    },
    {
        "Booking_ID":10001,
        "Customer_ID":'004',
        "Customer_Name":"Raj Kumar",
        "Customer_Image":"filepath",
        "Contact_Number":6698432271,
        "Contact_Email":"c.sureshkumar@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":13,
        "Gender":"Male",
        "Arrival_Date":"11/19/2022",
        "Arrival_Time":"11:41  PM",
        "Departure_Date":"11/23/2022",
        "Departure_Time":"8:21 AM",
        "Likes":"Comedy Show,Cooking",
        "Dislikes":"Screaming Children",
        "Other/Preferences":"Football",
    }

]


export {RecommendationData, Treading, Profile, eventDetailImage, EventDetail, DashboardEventDetail};
