const RecommendationData = [
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},

    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
]
const eventDetailImage = [
    {img:"Image120.jpg"},
    {img:"Image118.jpg"},
    {img:"Image122.jpg"},
    {img:"Image121.jpg"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const Treading = [
    {img:"trending1.jpg", rank:"one.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rank:"two.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg", rank:"three.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg", rank:"four.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rank:"five.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const SliderCardData = [
    {img:"trending1.jpg", rank:"one.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"recommend2.jpg", rank:"two.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"trending2.jpg", rank:"three.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"trending1.jpg", rank:"four.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod et dolore magna aliquyam erat…"},
    {img:"recommend2.jpg", rank:"five.svg", city:"Sindalah City", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod dolore magna aliquyam erat…"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const EventDetail =[
    [
        {
          "Event_ID": 10001,
          "Operator_ID": 20001,
          "Operator_Name": "Indigo",
          "Event_Category": "comedy show",
          "Event Name": "Stand Up Comedy",
          "Event Description": "Live comedy Performance infront of Audience",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "3:00 PM",
          "Event End Time": "7:30 PM",
          "Seat Booking Availability": 50,
          "Event Location": "Sindalah City",
          "Event Status": "Not Started",
          "Event_Capacity": 300,
          "Overall Event Rating": 3.8,
          "Operator Rating": 3
        },
        {
          "Event_ID": 10002,
          "Operator_ID": 20002,
          "Operator_Name": "Dark Roast",
          "Event_Category": "Fashion Shows",
          "Event Name": "RAMP Walk",
          "Event Description": "Manish Malhotra's new upcoming line clothing",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "7:00 PM",
          "Event End Time": "11:00 PM",
          "Seat Booking Availability": 20,
          "Event Location": "Sindalah City",
          "Event Status": "Not Started",
          "Event_Capacity": 200,
          "Overall Event Rating": 4.8,
          "Operator Rating": 4
        },
        {
          "Event_ID": 10003,
          "Operator_ID": 20003,
          "Operator_Name": "Basket of gold",
          "Event_Category": "Plays",
          "Event Name": "Othelo",
          "Event Description": "Shakespear Othelo Play",
          "Event Start Date": "11/11/2022",
          "Event End Date": "11/30/2022",
          "Event Start Time": "10:00 PM",
          "Event End Time": "05:00 PM",
          "Seat Booking Availability": 20,
          "Event Location": "Sindalah City",
          "Event Status": "Not Started",
          "Event_Capacity": 300,
          "Overall Event Rating": 4.6,
          "Operator Rating": 5
        },
        {
          "Event_ID": 10004,
          "Operator_ID": 20003,
          "Operator_Name": "Basket of gold",
          "Event_Category": "Water Activity",
          "Event Name": "Surfing",
          "Event Description": "Surfing at leasure",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "03:00 PM",
          "Event End Time": "05:00 PM",
          "Seat Booking Availability": 20,
          "Event Location": "Sindalah City",
          "Event Status": "Over",
          "Event_Capacity": 100,
          "Overall Event Rating": 4.6,
          "Operator Rating": 3
        },
        {
          "Event_ID": 10005,
          "Operator_ID": 20004,
          "Operator_Name": "Northern lights",
          "Event_Category": "Golf",
          "Event Name": "Golf tournament",
          "Event Description": "Mens Golf League",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "02:00 PM",
          "Event End Time": "05:00 PM",
          "Seat Booking Availability": 30,
          "Event Location": "Sindalah City",
          "Event Status": "Over",
          "Event_Capacity": 250,
          "Overall Event Rating": 4.6,
          "Operator Rating": 4
        },
        {
          "Event_ID": 10006,
          "Operator_ID": 20005,
          "Operator_Name": "Eden Spring",
          "Event_Category": "concerts",
          "Event Name": "Singing",
          "Event Description": "Music Type - Rock",
          "Event Start Date": "11/12/2022",
          "Event End Date": "11/30/2022",
          "Event Start Time": "07:30 PM",
          "Event End Time": "11:00 PM",
          "Seat Booking Availability": 10,
          "Event Location": "Sindalah City",
          "Event Status": "Over",
          "Event_Capacity": 100,
          "Overall Event Rating": 4.4,
          "Operator Rating": 3
        },
        {
          "Event_ID": 10007,
          "Operator_ID": 20005,
          "Operator_Name": "Eden Spring",
          "Event_Category": "Cooking ",
          "Event Name": "cooking class",
          "Event Description": "Thai Cooking Class",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "07:30 PM",
          "Event End Time": "11:00 PM",
          "Seat Booking Availability": 5,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 150,
          "Overall Event Rating": 4.4,
          "Operator Rating": 4
        },
        {
          "Event_ID": 10008,
          "Operator_ID": 20006,
          "Operator_Name": "River Stone",
          "Event_Category": "Talks ",
          "Event Name": "Talks Shows",
          "Event Description": "Live Talk Shows",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "08:00 PM",
          "Event End Time": "10:30 PM",
          "Seat Booking Availability": 20,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 400,
          "Overall Event Rating": 4.8,
          "Operator Rating": 5
        },
        {
          "Event_ID": 10009,
          "Operator_ID": 20007,
          "Operator_Name": "Dancing leaf",
          "Event_Category": "Kite Surfing ",
          "Event Name": "Kite Surfing",
          "Event Description": "Age above 18+",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "10:00 PM",
          "Event End Time": "03:00 PM",
          "Seat Booking Availability": 5,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 200,
          "Overall Event Rating": 4.4,
          "Operator Rating": 4
        },
        {
          "Event_ID": 100010,
          "Operator_ID": 20008,
          "Operator_Name": "Painted Desert",
          "Event_Category": "Exhibitions ",
          "Event Name": "Book Exhibitions",
          "Event Description": "Historical Book Exhibitions",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/29/2022",
          "Event Start Time": "05:00 PM",
          "Event End Time": "10:30 PM",
          "Seat Booking Availability": 15,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 200,
          "Overall Event Rating": 4.6,
          "Operator Rating": 3
        },
        {
          "Event_ID": 100011,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event Name": "Jazz Concert",
          "Event Description": "Steam Down",
          "Event Start Date": "11/11/2022",
          "Event End Date": "11/11/2022",
          "Event Start Time": "05:00 PM",
          "Event End Time": "10:30 PM",
          "Seat Booking Availability": 20,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 100,
          "Overall Event Rating": 4.6,
          "Operator Rating": 3
        },
        {
          "Event_ID": 100012,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event Name": "Rock Concert",
          "Event Description": "Rolling Stone",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/10/2022",
          "Event Start Time": "05:00 PM",
          "Event End Time": "10:30 PM",
          "Seat Booking Availability": 5,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 50,
          "Overall Event Rating": 4.6,
          "Operator Rating": 3
        },
        {
          "Event_ID": 100013,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event Name": "Piano Classes",
          "Event Description": "Piano basics",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/10/2022",
          "Event Start Time": "05:00 PM",
          "Event End Time": "10:30 PM",
          "Seat Booking Availability": 5,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 20,
          "Overall Event Rating": 4.6,
          "Operator Rating": 3
        },
        {
          "Event_ID": 100014,
          "Operator_ID": 20003,
          "Operator_Name": "Basket of gold",
          "Event_Category": "carnival",
          "Event Name": "Sweet Wonderlaw",
          "Event Description": "Weekly carnival",
          "Event Start Date": "11/10/2022",
          "Event End Date": "11/10/2022",
          "Event Start Time": "05:00 PM",
          "Event End Time": "10:30 PM",
          "Seat Booking Availability": 5,
          "Event Location": "Sindalah City",
          "Event Status": "Not Sarted",
          "Event_Capacity": 20,
          "Overall Event Rating": 4.6,
          "Operator Rating": 3
        }
      ]
]
const Profile = [
    {
        "Booking_ID":10001,
        "Customer_ID":'001',
        "Customer_Name":"Jane Mathew",
        "Customer_Image":"filepath",
        "Contact_Number":8899112233,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":48,
        "dop":'08/01/1979',
        "Gender":"female",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Golf, Rooms",
        "Dislikes":"Walking for Long",
        "Other/Preferences":"NA",


    },
    {
        "Booking_ID":10001,
        "Customer_ID":'002',
        "Customer_Name":"Shane Mathew",
        "Customer_Image":"filepath",
        "Contact_Number":8699114455,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":50,
        "Gender":"male",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Music, Exploring",
        "Dislikes":"Walking for Long",
        "Other/Preferences":"NA",


    },

    {
        "Booking_ID":10001,
        "Customer_ID":'003',
        "Customer_Name":"Rose Mathey",
        "Customer_Image":"filepath",
        "Contact_Number":9877665544,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":48,
        "Gender":"female",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Cooking",
        "Dislikes":"Chinese food",
        "Other/Preferences":"NA",
    },
    {
        "Booking_ID":10001,
        "Customer_ID":'004',
        "Customer_Name":"Raj Kumar",
        "Customer_Image":"filepath",
        "Contact_Number":6698432271,
        "Contact_Email":"c.sureshkumar@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":13,
        "Gender":"Male",
        "Arrival_Date":"11/19/2022",
        "Arrival_Time":"11:41  PM",
        "Departure_Date":"11/23/2022",
        "Departure_Time":"8:21 AM",
        "Likes":"Comedy Show,Cooking",
        "Dislikes":"Screaming Children",
        "Other/Preferences":"Football",
    }

]


export {RecommendationData, Treading, Profile, eventDetailImage, EventDetail};
